name: Basic Application Tests

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:

  migration-job:
    runs-on: ubuntu-latest
    
    container: 
      image: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: warehouse
          POSTGRES_PASSWORD: warehouse
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
      - name: Install PSQL Client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
          
      - name: Checkout master
        uses: actions/checkout@v1
      - run: |
          cargo install sqlx-cli
          cargo sqlx database create
        env:
          DATABASE_UR: =postgres://postgres:warehouse@localhost/warehouse
