name: PostgreSQL and Rust CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:

  psql-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    
    steps:
      - name: Checkout warehouse code repo
        uses: actions/checkout@v3
      - name: Create a .env file
        # You may pin to the exact commit or the version.
        # uses: DeveloperRic/action-create-env@55154f178faf68afd619cd16f233e5d31489a892
        uses: DeveloperRic/action-create-env@v1.0.4
        with:
          full_text:
            DATABASE_URL=postgres://postgres:postgres@localhost:5432/warehouse
          # Directory to write the file to (defaults to .). Parent directories will NOT be created.

      - name: Install sqlX-cli
        run: cargo install sqlx-cli
        
      - name: Run sqlx commands
        run: cargo sqlx database create
        
      
        
      
