name: PostgreSQL and Rust CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:

  psql-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    
    steps:
      - name: Checkout warehouse code repo
        uses: actions/checkout@v3
        
      - name: Install sqlX-cli
        run: cargo install sqlx-cli
        
      - name: Run sqlx commands
        run: cargo sqlx database create
        
      
        
      
