name: Basic Application Tests

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:

  migration-job:
    runs-on: ubuntu-latest
    
    container: 
      image: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: warehouse
          POSTGRES_PASSWORD: warehouse
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
      - name: Install PSQL Client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
          
      - name: Checkout master
      - uses: actions/checkout@v1
      
      - name: Install sqlx-cli
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install sqlx-cli
          
      - name: Create sqlx database
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: sqlx database create
    env:
      DATABASE_UR: =postgres://postgres:warehouse@localhost/warehouse
